image: node:20

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: registry.gitlab.com/qldm/frontend

before_script:
  - docker --version
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME

deploy_dev:
  stage: deploy
  script:
    - docker-compose -f docker-compose.dev.yml up -d
  when: manual
  only:
    - develop

deploy_prod:
  stage: deploy
  script:
    - docker-compose -f docker-compose.prod.yml up -d
  when: manual
  only:
    - main
  except:
    - triggers
